/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;

public class LibraryTest {
	
	WebDriver driver;
	
	@Before
	public void openBrowser() {
		driver = new ChromeDriver();
	}
    
	@Test 
    public void testSomeLibraryMethod() throws InterruptedException {
        
		//Arrange
		String urlWiki = "https://en.wikipedia.org/wiki/Main_Page";
		String expectedResult = "FIFA World Cup";
		String idSearchBar = "searchInput";
		String xpathFirstLink = "//*[@id=\"mw-content-text\"]/div/p[1]/a";
		String idTitle = "firstHeading";
		
		//Act		
        driver.get(urlWiki);
        WebElement barreRecherche = driver.findElement(By.id(idSearchBar));
        barreRecherche.sendKeys("World Cup" + Keys.ENTER);

//        WebElement button = driver.findElement(By.name("btnK"));
//        button.click();
        
//        List<WebElement> buttons = driver.findElements(By.className("lsb"));
//        buttons.get(1).click();
        
        WebElement linkCup = driver.findElement(By.xpath(xpathFirstLink));
        linkCup.click();
        
        WebElement titleCup = driver.findElement(By.className(idTitle));

        //Assert
        Assert.assertEquals(expectedResult,titleCup.getText());
        
        Thread.sleep(5000);
        
    }
	
	@Test
	public void testFail() {
		Assert.assertTrue(true);;
	}
	
	@After
	public void closeBrowser(){
		driver.quit();
	}
}
